model: 'geoan'
n_geoab: 18
c_geoan: 108
window_sizes: [ 2,5,10 ]
num_heads: 3
down_sample: 4
r_expand: 2

fp: 32
# loss: 'nn.SmoothL1Loss()'
loss: 'LatitudeLoss()'
optimizer: 'AdamW'
pretrain:
resume:
batch_size: 3
balanced_gpu0: -1
epochs: 100
lr: 0.0001
decays: [ 20, 40, 60, 80, 90, 95]
gamma: 0.5
test_every: 1
log_lines: 10
log_path: "./experiments"
log_name:
cloudlog: off
repeat: 1
augment: 'off'

# produce
model_path: 'data/exclude/geoan.pt'
save_path: "./proc"

## hardware specification
# specify the GPUs you want to use. [0] means using the first GPU. [1,3] means using second and fourth GPU
gpu_ids: [ 0 ]
threads: 4
## data specification
# the path train and test dateset. You can download the dataset in this project
data_path: 'data/exclude'
train_start_date: [ 2020,1,1 ]
train_end_date: [ 2022,12,31 ]

valid_start_date: [ 2023,12,1 ]
valid_end_date: [ 2023,12,31 ]

skip_day: 30
